plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitalk.css,post.css]
      scripts : [gitalk.js, post.js]



title: "jenson博客"
email: ""
description: "jenson的博客"
github:
  username: miss55
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: "jenson"
    client_id: 7baa6de266c15f33620b
    client_secret: 062a9145340a528913deaaff504ba9721fe2f120

url: "https://www.wenyisong.cn"
imgrepo: "https://www.wenyisong.cn/static/img"

# url: "https://miss55.github.io/jenson"
# imgrepo: "https://miss55.github.io/jenson/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

